# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------

#
# Module manifest for module 'WSLBlobNFS'
#
# Generated by: Azure Blob NFS
#
# Generated on: 16-11-2023
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'WSLBlobNFS.psm1'

# Version number of this module.
# To-do:
# 1. Proper versioning of the script.
# 2. Automate the versioning and release process.
ModuleVersion = '1.0.5'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '7cb818d5-f678-481f-8d92-159c349760de'

# Author of this module
Author = 'Azure Blob NFS'

# Company or vendor of this module
CompanyName = 'Azure Blob NFS'

# Copyright statement for this module
Copyright = '(c) 2023 Azure Blob NFS. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Azure Blob NFS'

# Minimum version of the PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
# Export functions defined in wsindowsblobnfs.ps1
# Exported functions will auto-complete on the command line even if the module is not yet loaded.
FunctionsToExport = @('Install-WSLBlobNFS', 'Initialize-WSLBlobNFS', 'Mount-WSLBlobNFS', 'Dismount-WSLBlobNFS')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# Additional files besides these will not harm, but the files metioned here must be present.
FileList = @( 'WSLBlobNFS.psd1', 'WSLBlobNFS.psm1', 'wsl2_linux_script.sh', 'query_quota.sh')

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('windows', 'azure', 'storage', 'wsl2', 'automation', 'cloud', 'automation')

        # A URL to the license for this module.
        LicenseUri = 'https://mit-license.org/'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/BlobNFS-wsl2'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

